### ISSUE TITLE
 import utils,constants,config

### ISSUE THREAD

**Issue by babaz8** [aminblm/linkedin-application-bot#20]
I'm running it on mac getting this error

python3 linkedin.py
Traceback (most recent call last):
  File "/Users/.../linkedin-application-bot/linkedin.py", line 2, in <module>
    import utils,constants,config
  File "/Users/.../linkedin-application-bot/utils.py", line 112
    match job.casefold():
          ^
SyntaxError: invalid syntax

**Comment by adityauwu** [comment]
same issue, did you get the fix for this?

**Comment by babaz8** [comment]
> same issue, did you get the fix for this?

Nope I didn't unfortunately

**Comment by adityauwu** [comment]
Upgrade your python to latest version

**Comment by babaz8** [comment]
> Upgrade your python to latest version, cant use match in lower versions of python

Which version of Python are u using? I tried with 3.10

**Comment by adityauwu** [comment]
M using the latest pip and python, after that you would need to use it with chrome, firefox wont work

**Comment by babaz8** [comment]
> M using the latest pip and python, after that you would need to use it with chrome, firefox wont work

Frankly speaking I don't know how to switch it using chrome.
BTW i'm executing it with python 3.11

**Comment by adityauwu** [comment]
Can you paste the error that you are getting

**Comment by babaz8** [comment]
> Can you paste the error that you are getting

Error in main: 'str' object has no attribute 'capabilities'
---Took: 0 minute(s).
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 71, in driver_location
    browser = options.capabilities["browserName"]
              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXX/linkedin-application-bot/linkedin.py", line 241, in <module>
    Linkedin().linkJobApply()
    ^^^^^^^^^^
  File "/Users/XXX/linkedin-application-bot/linkedin.py", line 38, in __init__
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 71, in driver_location
    browser = options.capabilities["browserName"]
              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXX/linkedin-application-bot/linkedin.py", line 247, in <module>
    Linkedin().driver.quit()
    ^^^^^^^^^^
  File "/Users/XXX/linkedin-application-bot/linkedin.py", line 38, in __init__
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'capabilities'

**Comment by wodsuz** [comment]
Please refer to the original repo https://github.com/wodsuz/EasyApplyJobsBot this duplicate on doesn't get updates nor backed by our team

**Comment by aminblm** [comment]
🌟 Hey everyone, I've picked up the maintenance on this. 🛠️ Is this issue still relevant, or have we found a solution? Thanks for bringing it up! 👏
