### ISSUE TITLE
FF opens two apps using https://hostlocal

### ISSUE THREAD

**Issue by AVOCAVentures** [aminblm/linkedin-application-bot#5]
After hard quitting FF and running the linkedin.py these errors have come up overnight without changing any code;

It will run as per normal then fail before hitting the 'Easy Apply' button and throw a error;

A copy of Firefox is already open. Only one copy of Firefox can be open at a time.

HERE IS A VIDEO OF THE ISSUE: https://drive.google.com/file/d/1QWJJW1Rnz_It3jTlftyQvj4wxWamOUoK/view?usp=sharing

This is the terminal output;

(base) iBartMacBook-Pro3:linkedin-apply-bot-main bartjawien$ python linkedin.py
Urls are created successfully, now the bot will visit those urls.
Error in main: Message: Unable to locate element: //small; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:395:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16

---Took: 0 minute(s).
Traceback (most recent call last):
  File "/Users/bartjawien/Downloads/linkedin-apply-bot-main/linkedin.py", line 249, in <module>
    Linkedin().linkJobApply()
  File "/Users/bartjawien/Downloads/linkedin-apply-bot-main/linkedin.py", line 76, in linkJobApply
    totalJobs = self.driver.find_element(By.XPATH,'//small').text
  File "/Users/bartjawien/anaconda3/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 740, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/Users/bartjawien/anaconda3/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/Users/bartjawien/anaconda3/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //small; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:395:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bartjawien/Downloads/linkedin-apply-bot-main/linkedin.py", line 255, in <module>
    Linkedin().driver.quit()
  File "/Users/bartjawien/Downloads/linkedin-apply-bot-main/linkedin.py", line 36, in __init__
    self.driver = webdriver.Firefox(options=utils.browserOptions(),service=Service(executable_path=GeckoDriverManager().install()))
  File "/Users/bartjawien/anaconda3/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 68, in __init__
    super().__init__(command_executor=executor, options=self.options)
  File "/Users/bartjawien/anaconda3/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/Users/bartjawien/anaconda3/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/Users/bartjawien/anaconda3/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/Users/bartjawien/anaconda3/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Socket timeout reading Marionette handshake data: EOF reading marionette message

(base) iBartMacBook-Pro3:linkedin-apply-bot-main bartjawien$

**Comment by wodsuz** [comment]
Please refer to the original repo https://github.com/wodsuz/EasyApplyJobsBot this duplicate on doesn't get updates nor backed by our team
